//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Faculty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faculty()
        {
            this.Specialty = new HashSet<Specialty>();
        }

        [Required(ErrorMessage = "Empty field is not allowed")]
        [StringLength(3, ErrorMessage = "{0}'s length should be between {2} and {1}.", MinimumLength = 2)]
        public string facultyName { get; set; }
        [Required(ErrorMessage = "Empty field is not allowed")]
        [StringLength(100, ErrorMessage = "{0}'s length should be between {2} and {1}.", MinimumLength = 5)]
        public string fullNameOfDirector { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Specialty> Specialty { get; set; }
    }
}
