//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.Student = new HashSet<Student>();
        }
    
        [Required(ErrorMessage = "Empty field is not allowed")]
        [RegularExpression(@"(\D\D\D\D)-\d\d-\d\d", ErrorMessage = "Incorrect groupCode format. GroupCode should be in format like 'Asub-19-02'")]
        public string groupCode { get; set; }
        [Required(ErrorMessage = "Empty field is not allowed")]
        [StringLength(4, ErrorMessage = "{0}'s should be between {2} and {1}.", MinimumLength = 3)]
        public string specialtyCode { get; set; }
        [Required(ErrorMessage = "Empty field is not allowed")]
        [Range(1930, 2021, ErrorMessage = "yearAdmition value should be between 1930 and 2021")]
        public short yearAdmition { get; set; }
    
        public virtual Specialty Specialty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }
    }
}
