//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class studBDEntities : DbContext
    {
        public studBDEntities()
            : base("name=studBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Faculty> Faculty { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Specialty> Specialty { get; set; }
        public virtual DbSet<Student> Student { get; set; }
    
        public virtual int addFaculty(string facultyName, string fullNameOfDirector)
        {
            var facultyNameParameter = facultyName != null ?
                new ObjectParameter("facultyName", facultyName) :
                new ObjectParameter("facultyName", typeof(string));
    
            var fullNameOfDirectorParameter = fullNameOfDirector != null ?
                new ObjectParameter("fullNameOfDirector", fullNameOfDirector) :
                new ObjectParameter("fullNameOfDirector", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addFaculty", facultyNameParameter, fullNameOfDirectorParameter);
        }
    
        public virtual int addGroup(string groupCode, string specialtyCode, Nullable<short> yearAdmition)
        {
            var groupCodeParameter = groupCode != null ?
                new ObjectParameter("groupCode", groupCode) :
                new ObjectParameter("groupCode", typeof(string));
    
            var specialtyCodeParameter = specialtyCode != null ?
                new ObjectParameter("specialtyCode", specialtyCode) :
                new ObjectParameter("specialtyCode", typeof(string));
    
            var yearAdmitionParameter = yearAdmition.HasValue ?
                new ObjectParameter("yearAdmition", yearAdmition) :
                new ObjectParameter("yearAdmition", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addGroup", groupCodeParameter, specialtyCodeParameter, yearAdmitionParameter);
        }
    
        public virtual int addSpecialty(string specialtyCode, string facultyName, string qualification)
        {
            var specialtyCodeParameter = specialtyCode != null ?
                new ObjectParameter("specialtyCode", specialtyCode) :
                new ObjectParameter("specialtyCode", typeof(string));
    
            var facultyNameParameter = facultyName != null ?
                new ObjectParameter("facultyName", facultyName) :
                new ObjectParameter("facultyName", typeof(string));
    
            var qualificationParameter = qualification != null ?
                new ObjectParameter("qualification", qualification) :
                new ObjectParameter("qualification", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addSpecialty", specialtyCodeParameter, facultyNameParameter, qualificationParameter);
        }
    
        public virtual int addStudent(Nullable<int> studentNumber, string groupCode, string fullName, Nullable<int> fathersSalary, Nullable<int> mothersSalary, Nullable<byte> numFamMembers)
        {
            var studentNumberParameter = studentNumber.HasValue ?
                new ObjectParameter("studentNumber", studentNumber) :
                new ObjectParameter("studentNumber", typeof(int));
    
            var groupCodeParameter = groupCode != null ?
                new ObjectParameter("groupCode", groupCode) :
                new ObjectParameter("groupCode", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var fathersSalaryParameter = fathersSalary.HasValue ?
                new ObjectParameter("fathersSalary", fathersSalary) :
                new ObjectParameter("fathersSalary", typeof(int));
    
            var mothersSalaryParameter = mothersSalary.HasValue ?
                new ObjectParameter("mothersSalary", mothersSalary) :
                new ObjectParameter("mothersSalary", typeof(int));
    
            var numFamMembersParameter = numFamMembers.HasValue ?
                new ObjectParameter("numFamMembers", numFamMembers) :
                new ObjectParameter("numFamMembers", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("addStudent", studentNumberParameter, groupCodeParameter, fullNameParameter, fathersSalaryParameter, mothersSalaryParameter, numFamMembersParameter);
        }
    
        public virtual int deleteFaculty(string facultyName)
        {
            var facultyNameParameter = facultyName != null ?
                new ObjectParameter("facultyName", facultyName) :
                new ObjectParameter("facultyName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteFaculty", facultyNameParameter);
        }
    
        public virtual int deleteGroup(string groupCode)
        {
            var groupCodeParameter = groupCode != null ?
                new ObjectParameter("groupCode", groupCode) :
                new ObjectParameter("groupCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteGroup", groupCodeParameter);
        }
    
        public virtual int deleteSpecialty(string specialtyCode)
        {
            var specialtyCodeParameter = specialtyCode != null ?
                new ObjectParameter("specialtyCode", specialtyCode) :
                new ObjectParameter("specialtyCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteSpecialty", specialtyCodeParameter);
        }
    
        public virtual int deleteStudent(Nullable<int> studentNumber)
        {
            var studentNumberParameter = studentNumber.HasValue ?
                new ObjectParameter("studentNumber", studentNumber) :
                new ObjectParameter("studentNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deleteStudent", studentNumberParameter);
        }
    
        public virtual int editGroup(string groupCode, string specialtyCode, Nullable<short> yearAdmition)
        {
            var groupCodeParameter = groupCode != null ?
                new ObjectParameter("groupCode", groupCode) :
                new ObjectParameter("groupCode", typeof(string));
    
            var specialtyCodeParameter = specialtyCode != null ?
                new ObjectParameter("specialtyCode", specialtyCode) :
                new ObjectParameter("specialtyCode", typeof(string));
    
            var yearAdmitionParameter = yearAdmition.HasValue ?
                new ObjectParameter("yearAdmition", yearAdmition) :
                new ObjectParameter("yearAdmition", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editGroup", groupCodeParameter, specialtyCodeParameter, yearAdmitionParameter);
        }
    
        public virtual int editSpecialty(string specialtyCode, string facultyName, string qualification)
        {
            var specialtyCodeParameter = specialtyCode != null ?
                new ObjectParameter("specialtyCode", specialtyCode) :
                new ObjectParameter("specialtyCode", typeof(string));
    
            var facultyNameParameter = facultyName != null ?
                new ObjectParameter("facultyName", facultyName) :
                new ObjectParameter("facultyName", typeof(string));
    
            var qualificationParameter = qualification != null ?
                new ObjectParameter("qualification", qualification) :
                new ObjectParameter("qualification", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editSpecialty", specialtyCodeParameter, facultyNameParameter, qualificationParameter);
        }
    
        public virtual int editStudent(Nullable<int> studentNumber, string groupCode, string fullName, Nullable<int> fathersSalary, Nullable<int> mothersSalary, Nullable<byte> numFamMembers)
        {
            var studentNumberParameter = studentNumber.HasValue ?
                new ObjectParameter("studentNumber", studentNumber) :
                new ObjectParameter("studentNumber", typeof(int));
    
            var groupCodeParameter = groupCode != null ?
                new ObjectParameter("groupCode", groupCode) :
                new ObjectParameter("groupCode", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var fathersSalaryParameter = fathersSalary.HasValue ?
                new ObjectParameter("fathersSalary", fathersSalary) :
                new ObjectParameter("fathersSalary", typeof(int));
    
            var mothersSalaryParameter = mothersSalary.HasValue ?
                new ObjectParameter("mothersSalary", mothersSalary) :
                new ObjectParameter("mothersSalary", typeof(int));
    
            var numFamMembersParameter = numFamMembers.HasValue ?
                new ObjectParameter("numFamMembers", numFamMembers) :
                new ObjectParameter("numFamMembers", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editStudent", studentNumberParameter, groupCodeParameter, fullNameParameter, fathersSalaryParameter, mothersSalaryParameter, numFamMembersParameter);
        }
    
        public virtual int fillFaculty(Nullable<int> i)
        {
            var iParameter = i.HasValue ?
                new ObjectParameter("i", i) :
                new ObjectParameter("i", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("fillFaculty", iParameter);
        }
    
        public virtual int fillGroup(Nullable<int> i)
        {
            var iParameter = i.HasValue ?
                new ObjectParameter("i", i) :
                new ObjectParameter("i", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("fillGroup", iParameter);
        }
    
        public virtual int fillSpecialty(Nullable<int> i)
        {
            var iParameter = i.HasValue ?
                new ObjectParameter("i", i) :
                new ObjectParameter("i", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("fillSpecialty", iParameter);
        }
    
        public virtual int fillStudent(Nullable<int> i)
        {
            var iParameter = i.HasValue ?
                new ObjectParameter("i", i) :
                new ObjectParameter("i", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("fillStudent", iParameter);
        }
    
        public virtual ObjectResult<Search1_Result> Search1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search1_Result>("Search1");
        }
    
        public virtual ObjectResult<Search1_1_Result> Search1_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search1_1_Result>("Search1_1");
        }
    
        public virtual ObjectResult<Search2Web_Result> Search2Web(string groupCode, Nullable<int> avgSalary)
        {
            var groupCodeParameter = groupCode != null ?
                new ObjectParameter("groupCode", groupCode) :
                new ObjectParameter("groupCode", typeof(string));
    
            var avgSalaryParameter = avgSalary.HasValue ?
                new ObjectParameter("avgSalary", avgSalary) :
                new ObjectParameter("avgSalary", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search2Web_Result>("Search2Web", groupCodeParameter, avgSalaryParameter);
        }
    
        public virtual ObjectResult<showFaculty_Result> showFaculty()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showFaculty_Result>("showFaculty");
        }
    
        public virtual ObjectResult<showGroup_Result> showGroup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showGroup_Result>("showGroup");
        }
    
        public virtual ObjectResult<showSpecialty_Result> showSpecialty()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showSpecialty_Result>("showSpecialty");
        }
    
        public virtual ObjectResult<showStudent_Result> showStudent()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<showStudent_Result>("showStudent");
        }
    
        public virtual ObjectResult<Search2_Result> Search2(string groupCode, Nullable<int> avgSalary)
        {
            var groupCodeParameter = groupCode != null ?
                new ObjectParameter("groupCode", groupCode) :
                new ObjectParameter("groupCode", typeof(string));
    
            var avgSalaryParameter = avgSalary.HasValue ?
                new ObjectParameter("avgSalary", avgSalary) :
                new ObjectParameter("avgSalary", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search2_Result>("Search2", groupCodeParameter, avgSalaryParameter);
        }
    
        public virtual int editFaculty(string facultyName, string fullNameOfDirector)
        {
            var facultyNameParameter = facultyName != null ?
                new ObjectParameter("facultyName", facultyName) :
                new ObjectParameter("facultyName", typeof(string));
    
            var fullNameOfDirectorParameter = fullNameOfDirector != null ?
                new ObjectParameter("fullNameOfDirector", fullNameOfDirector) :
                new ObjectParameter("fullNameOfDirector", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("editFaculty", facultyNameParameter, fullNameOfDirectorParameter);
        }
    }
}
