//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Specialty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specialty()
        {
            this.Group = new HashSet<Group>();
        }

        [Required(ErrorMessage = "Empty field is not allowed")]
        [StringLength(4, ErrorMessage = "{0}'s length should be between {2} and {1}.", MinimumLength = 3)]
        public string specialtyCode { get; set; }
        public string facultyName { get; set; }
        [StringLength(10, ErrorMessage = "{0}'s length should be between {2} and {1}. Allowed values for this field: 'Master', 'Bachelor' and 'Specialist'.", MinimumLength = 6)]
        public string qualification { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Group { get; set; }
    }
}
