//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [Required(ErrorMessage = "Empty field is not allowed")]
        [Range(10000000, 99999999, ErrorMessage = "{0}'s value should be between {1} and {2}")]
        public int studentNumber { get; set; }
        [Required(ErrorMessage = "Empty field is not allowed")]
        public string groupCode { get; set; }
        [Required(ErrorMessage = "Empty field is not allowed")]
        [StringLength(100, ErrorMessage = "{0}'s length should be between {2} and {1}.", MinimumLength = 5)]
        public string fullName { get; set; }
        [Required(ErrorMessage = "Empty field is not allowed")]
        [Range(30000, 350000, ErrorMessage = "{0}'s value should be between {1} and {2}")]
        public int fathersSalary { get; set; }
        [Required(ErrorMessage = "Empty field is not allowed")]
        [Range(30000, 350000, ErrorMessage = "{0}'s value should be between {1} and {2}")]
        public int mothersSalary { get; set; }
        [Required(ErrorMessage = "Empty field is not allowed")]
        [Range(2, 7, ErrorMessage = "{0}'s value should be between {1} and {2}")]
        public byte numFamMembers { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
